name: Siem Detection
language: python
variables:
  - name: log_data
    inputType: InputTopic
    description: This is the input topic for log data
    defaultValue: zeek-http-logs
    required: true
  - name: alerts
    inputType: OutputTopic
    description: This is the output topic for siem alerts
    defaultValue: alerts
    required: true
  - name: log_info
    inputType: FreeText
    description: Consumes zeek logs
    defaultValue: zeek
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
