name: Sigma Rules Manager
language: nodejs
variables:
  - name: input
    inputType: InputTopic
    description: The topic to read from
    defaultValue: alerts
    required: true
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1qVTBRVE01TmtJNVJqSTNOVEpFUlVSRFF6WXdRVFF4TjBSRk56SkNNekpFUWpBNFFqazBSUSJ9.eyJodHRwczovL3F1aXguYWkvb3JnX2lkIjoibWF0dCIsImh0dHBzOi8vcXVpeC5haS9yb2xlcyI6IiIsImlzcyI6Imh0dHBzOi8vYXV0aC5xdWl4LmFpLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA1NTY4NDM4MDU3OTY2MTY3OTQ5IiwiYXVkIjpbInF1aXgiLCJodHRwczovL2xvZ2ljYWwtcGxhdGZvcm0uZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcwMTY3MzI2OSwiZXhwIjoxNzA0MjY1MjY5LCJhenAiOiIwem1XZkpka2l1R1BpSld5cFNDQThyS2FWdmZQREtMSSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.KSCBkeNT9BmTNWKH9xM0GJkdgFAnM2cy_V0BYAHdlRaYQp4A9ytOIk2dwvWx6QN4Y7ZmVSshLKewBbKjGAsZmINYuV6hskiIH9tM4WwjdYMcOmsSitjIGSBOKWcevUvylwQxmqPhn3O6WCoFfFHdLOW_aXM2w9nnb2D24HpIdZtYkBLVDgZXOz3A6NquQR133RUg20Vx57hKZG2fc58UvmUmF2fq0fW42kWpqCNjfgYZ4zcUt_Ti1sD8f9ChLiTDxqo21WCP7Lr_7fRO4-0ZsYFLAA63UQvQ6hIbrZYxG7u6ZteuvhCeSs5JiddRxhGZ06xP9tMsMnpGojP7opsVag
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/services/quix.ts
