name: UI
language: nodejs
variables:
  - name: input
    inputType: InputTopic
    description: The topic to read from
    defaultValue: alerts
    required: true
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: pat-ca3e35a2779f45eea3fe9c3a779698b6
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/services/quix.ts
